//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcAdmingirisli.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notlar
    {
        public Nullable<int> DersNo { get; set; }
        public Nullable<int> OgrenciNo { get; set; }
        public string DersYili { get; set; }
        public Nullable<decimal> Vize { get; set; }
        public decimal Final { get; set; }
    
        public virtual Dersler Dersler { get; set; }
        public virtual Ogrenciler Ogrenciler { get; set; }
    }
}
